// <auto-generated />
using System;
using CarRentalApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRentalApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260323204144_Images")]
    partial class Images
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarRentalApp.Models.Car", b =>
                {
                    b.Property<string>("IdCar")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DoorsCount")
                        .HasColumnType("int");

                    b.Property<double>("EngineCapacity")
                        .HasColumnType("float");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("GearboxType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PricePerDay")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SeatsCount")
                        .HasColumnType("int");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrunkCapacity")
                        .HasColumnType("int");

                    b.HasKey("IdCar");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            IdCar = "C1",
                            BodyType = "Sedan",
                            Brand = "Toyota",
                            DoorsCount = 5,
                            EngineCapacity = 1.8,
                            FuelType = "Hybrid",
                            GearboxType = "Manual",
                            ImagePath = "/Images/ToyotaCorolla.png",
                            Model = "Corolla",
                            PricePerDay = 150m,
                            SeatsCount = 5,
                            Segment = "C",
                            TrunkCapacity = 470
                        },
                        new
                        {
                            IdCar = "C2",
                            BodyType = "Sedan",
                            Brand = "BMW",
                            DoorsCount = 4,
                            EngineCapacity = 2.0,
                            FuelType = "Petrol",
                            GearboxType = "Automatic",
                            ImagePath = "/Images/BmwModel3.png",
                            Model = "3 Series",
                            PricePerDay = 300m,
                            SeatsCount = 5,
                            Segment = "D",
                            TrunkCapacity = 480
                        },
                        new
                        {
                            IdCar = "C3",
                            BodyType = "Sedan",
                            Brand = "Tesla",
                            DoorsCount = 4,
                            EngineCapacity = 0.0,
                            FuelType = "Electric",
                            GearboxType = "Automatic",
                            ImagePath = "/Images/TeslaModel3.png",
                            Model = "Model 3",
                            PricePerDay = 450m,
                            SeatsCount = 5,
                            Segment = "C",
                            TrunkCapacity = 542
                        },
                        new
                        {
                            IdCar = "C4",
                            BodyType = "Liftback",
                            Brand = "Skoda",
                            DoorsCount = 5,
                            EngineCapacity = 1.3999999999999999,
                            FuelType = "Petrol",
                            GearboxType = "Automatic",
                            ImagePath = "/Images/SkodaOctavia3.png",
                            Model = "Octavia 3",
                            PricePerDay = 180m,
                            SeatsCount = 5,
                            Segment = "C",
                            TrunkCapacity = 610
                        },
                        new
                        {
                            IdCar = "C5",
                            BodyType = "Combi",
                            Brand = "Skoda",
                            DoorsCount = 5,
                            EngineCapacity = 2.0,
                            FuelType = "Diesel",
                            GearboxType = "Automatic",
                            ImagePath = "octavia4.jpg",
                            Model = "Octavia 4",
                            PricePerDay = 220m,
                            SeatsCount = 5,
                            Segment = "C",
                            TrunkCapacity = 600
                        },
                        new
                        {
                            IdCar = "C6",
                            BodyType = "Hatchback",
                            Brand = "Skoda",
                            DoorsCount = 5,
                            EngineCapacity = 1.0,
                            FuelType = "Petrol",
                            GearboxType = "Manual",
                            ImagePath = "fabia3.jpg",
                            Model = "Fabia 3",
                            PricePerDay = 120m,
                            SeatsCount = 5,
                            Segment = "B",
                            TrunkCapacity = 330
                        },
                        new
                        {
                            IdCar = "C7",
                            BodyType = "Hatchback",
                            Brand = "Skoda",
                            DoorsCount = 5,
                            EngineCapacity = 1.0,
                            FuelType = "Petrol",
                            GearboxType = "Manual",
                            ImagePath = "fabia4.jpg",
                            Model = "Fabia 4",
                            PricePerDay = 140m,
                            SeatsCount = 5,
                            Segment = "B",
                            TrunkCapacity = 380
                        },
                        new
                        {
                            IdCar = "C8",
                            BodyType = "Sedan",
                            Brand = "Skoda",
                            DoorsCount = 5,
                            EngineCapacity = 2.0,
                            FuelType = "Diesel",
                            GearboxType = "Automatic",
                            ImagePath = "superb3.jpg",
                            Model = "Superb 3",
                            PricePerDay = 280m,
                            SeatsCount = 5,
                            Segment = "D",
                            TrunkCapacity = 625
                        },
                        new
                        {
                            IdCar = "C9",
                            BodyType = "Combi",
                            Brand = "Skoda",
                            DoorsCount = 5,
                            EngineCapacity = 2.0,
                            FuelType = "Diesel",
                            GearboxType = "Automatic",
                            ImagePath = "superb4.jpg",
                            Model = "Superb 4",
                            PricePerDay = 350m,
                            SeatsCount = 5,
                            Segment = "D",
                            TrunkCapacity = 690
                        },
                        new
                        {
                            IdCar = "C10",
                            BodyType = "Hatchback",
                            Brand = "Volkswagen",
                            DoorsCount = 5,
                            EngineCapacity = 1.2,
                            FuelType = "Petrol",
                            GearboxType = "Manual",
                            ImagePath = "polo5.jpg",
                            Model = "Polo 5",
                            PricePerDay = 110m,
                            SeatsCount = 5,
                            Segment = "B",
                            TrunkCapacity = 280
                        },
                        new
                        {
                            IdCar = "C11",
                            BodyType = "Hatchback",
                            Brand = "Volkswagen",
                            DoorsCount = 5,
                            EngineCapacity = 1.0,
                            FuelType = "Petrol",
                            GearboxType = "Manual",
                            ImagePath = "polo6.jpg",
                            Model = "Polo 6",
                            PricePerDay = 135m,
                            SeatsCount = 5,
                            Segment = "B",
                            TrunkCapacity = 351
                        },
                        new
                        {
                            IdCar = "C12",
                            BodyType = "Hatchback",
                            Brand = "Volkswagen",
                            DoorsCount = 5,
                            EngineCapacity = 1.3999999999999999,
                            FuelType = "Petrol",
                            GearboxType = "Manual",
                            ImagePath = "golf6.jpg",
                            Model = "Golf 6",
                            PricePerDay = 150m,
                            SeatsCount = 5,
                            Segment = "C",
                            TrunkCapacity = 350
                        },
                        new
                        {
                            IdCar = "C13",
                            BodyType = "Hatchback",
                            Brand = "Volkswagen",
                            DoorsCount = 5,
                            EngineCapacity = 1.6000000000000001,
                            FuelType = "Diesel",
                            GearboxType = "Automatic",
                            ImagePath = "golf7.jpg",
                            Model = "Golf 7",
                            PricePerDay = 170m,
                            SeatsCount = 5,
                            Segment = "C",
                            TrunkCapacity = 380
                        },
                        new
                        {
                            IdCar = "C14",
                            BodyType = "Hatchback",
                            Brand = "Volkswagen",
                            DoorsCount = 5,
                            EngineCapacity = 1.5,
                            FuelType = "Hybrid",
                            GearboxType = "Automatic",
                            ImagePath = "/Images/VwGolf8.png",
                            Model = "Golf 8",
                            PricePerDay = 210m,
                            SeatsCount = 5,
                            Segment = "C",
                            TrunkCapacity = 381
                        },
                        new
                        {
                            IdCar = "C15",
                            BodyType = "Sedan",
                            Brand = "Volkswagen",
                            DoorsCount = 4,
                            EngineCapacity = 2.0,
                            FuelType = "Diesel",
                            GearboxType = "Manual",
                            ImagePath = "passat7.jpg",
                            Model = "Passat 7",
                            PricePerDay = 190m,
                            SeatsCount = 5,
                            Segment = "D",
                            TrunkCapacity = 565
                        },
                        new
                        {
                            IdCar = "C16",
                            BodyType = "Combi",
                            Brand = "Volkswagen",
                            DoorsCount = 5,
                            EngineCapacity = 2.0,
                            FuelType = "Diesel",
                            GearboxType = "Automatic",
                            ImagePath = "passat8.jpg",
                            Model = "Passat 8",
                            PricePerDay = 230m,
                            SeatsCount = 5,
                            Segment = "D",
                            TrunkCapacity = 650
                        },
                        new
                        {
                            IdCar = "C17",
                            BodyType = "Combi",
                            Brand = "Volkswagen",
                            DoorsCount = 5,
                            EngineCapacity = 2.0,
                            FuelType = "Diesel",
                            GearboxType = "Automatic",
                            ImagePath = "/Images/VwPassat9.png",
                            Model = "Passat 9",
                            PricePerDay = 320m,
                            SeatsCount = 5,
                            Segment = "D",
                            TrunkCapacity = 690
                        },
                        new
                        {
                            IdCar = "C18",
                            BodyType = "Hatchback",
                            Brand = "Seat",
                            DoorsCount = 5,
                            EngineCapacity = 1.3999999999999999,
                            FuelType = "Petrol",
                            GearboxType = "Manual",
                            ImagePath = "leon3.jpg",
                            Model = "Leon 3",
                            PricePerDay = 160m,
                            SeatsCount = 5,
                            Segment = "C",
                            TrunkCapacity = 380
                        },
                        new
                        {
                            IdCar = "C19",
                            BodyType = "Hatchback",
                            Brand = "Seat",
                            DoorsCount = 5,
                            EngineCapacity = 1.5,
                            FuelType = "Petrol",
                            GearboxType = "Automatic",
                            ImagePath = "leon4.jpg",
                            Model = "Leon 4",
                            PricePerDay = 200m,
                            SeatsCount = 5,
                            Segment = "C",
                            TrunkCapacity = 380
                        },
                        new
                        {
                            IdCar = "C20",
                            BodyType = "Hatchback",
                            Brand = "Seat",
                            DoorsCount = 5,
                            EngineCapacity = 1.2,
                            FuelType = "Petrol",
                            GearboxType = "Manual",
                            ImagePath = "ibiza4.jpg",
                            Model = "Ibiza 4",
                            PricePerDay = 110m,
                            SeatsCount = 5,
                            Segment = "B",
                            TrunkCapacity = 292
                        },
                        new
                        {
                            IdCar = "C21",
                            BodyType = "Hatchback",
                            Brand = "Seat",
                            DoorsCount = 5,
                            EngineCapacity = 1.0,
                            FuelType = "Petrol",
                            GearboxType = "Manual",
                            ImagePath = "ibiza5.jpg",
                            Model = "Ibiza 5",
                            PricePerDay = 130m,
                            SeatsCount = 5,
                            Segment = "B",
                            TrunkCapacity = 355
                        },
                        new
                        {
                            IdCar = "C22",
                            BodyType = "Hatchback",
                            Brand = "Audi",
                            DoorsCount = 5,
                            EngineCapacity = 1.5,
                            FuelType = "Petrol",
                            GearboxType = "Automatic",
                            ImagePath = "audia3.jpg",
                            Model = "A3",
                            PricePerDay = 250m,
                            SeatsCount = 5,
                            Segment = "C",
                            TrunkCapacity = 380
                        },
                        new
                        {
                            IdCar = "C23",
                            BodyType = "Hatchback",
                            Brand = "Audi",
                            DoorsCount = 5,
                            EngineCapacity = 2.0,
                            FuelType = "Petrol",
                            GearboxType = "Automatic",
                            ImagePath = "audis3.jpg",
                            Model = "S3",
                            PricePerDay = 500m,
                            SeatsCount = 5,
                            Segment = "C",
                            TrunkCapacity = 325
                        },
                        new
                        {
                            IdCar = "C24",
                            BodyType = "Hatchback",
                            Brand = "Audi",
                            DoorsCount = 5,
                            EngineCapacity = 2.5,
                            FuelType = "Petrol",
                            GearboxType = "Automatic",
                            ImagePath = "/Images/AudiRS3.png",
                            Model = "RS3",
                            PricePerDay = 850m,
                            SeatsCount = 5,
                            Segment = "C",
                            TrunkCapacity = 282
                        },
                        new
                        {
                            IdCar = "C25",
                            BodyType = "Sedan",
                            Brand = "Audi",
                            DoorsCount = 4,
                            EngineCapacity = 2.0,
                            FuelType = "Diesel",
                            GearboxType = "Automatic",
                            ImagePath = "/Images/AudiA4.png",
                            Model = "A4",
                            PricePerDay = 300m,
                            SeatsCount = 5,
                            Segment = "D",
                            TrunkCapacity = 460
                        },
                        new
                        {
                            IdCar = "C26",
                            BodyType = "Sedan",
                            Brand = "Audi",
                            DoorsCount = 4,
                            EngineCapacity = 3.0,
                            FuelType = "Diesel",
                            GearboxType = "Automatic",
                            ImagePath = "audis4.jpg",
                            Model = "S4",
                            PricePerDay = 600m,
                            SeatsCount = 5,
                            Segment = "D",
                            TrunkCapacity = 420
                        },
                        new
                        {
                            IdCar = "C27",
                            BodyType = "Combi",
                            Brand = "Audi",
                            DoorsCount = 5,
                            EngineCapacity = 2.8999999999999999,
                            FuelType = "Petrol",
                            GearboxType = "Automatic",
                            ImagePath = "audirs4.jpg",
                            Model = "RS4",
                            PricePerDay = 1000m,
                            SeatsCount = 5,
                            Segment = "D",
                            TrunkCapacity = 495
                        },
                        new
                        {
                            IdCar = "C28",
                            BodyType = "Hatchback",
                            Brand = "Opel",
                            DoorsCount = 5,
                            EngineCapacity = 1.2,
                            FuelType = "Petrol",
                            GearboxType = "Manual",
                            ImagePath = "corsa.jpg",
                            Model = "Corsa",
                            PricePerDay = 115m,
                            SeatsCount = 5,
                            Segment = "B",
                            TrunkCapacity = 309
                        },
                        new
                        {
                            IdCar = "C29",
                            BodyType = "SUV",
                            Brand = "Kia",
                            DoorsCount = 5,
                            EngineCapacity = 1.6000000000000001,
                            FuelType = "Petrol",
                            GearboxType = "Manual",
                            ImagePath = "/Images/KiaSportage.png",
                            Model = "Sportage",
                            PricePerDay = 240m,
                            SeatsCount = 5,
                            Segment = "SUV",
                            TrunkCapacity = 591
                        },
                        new
                        {
                            IdCar = "C30",
                            BodyType = "Crossover",
                            Brand = "Kia",
                            DoorsCount = 5,
                            EngineCapacity = 1.2,
                            FuelType = "Petrol",
                            GearboxType = "Manual",
                            ImagePath = "stonic.jpg",
                            Model = "Stonic",
                            PricePerDay = 160m,
                            SeatsCount = 5,
                            Segment = "B-SUV",
                            TrunkCapacity = 332
                        },
                        new
                        {
                            IdCar = "C31",
                            BodyType = "SUV",
                            Brand = "Volvo",
                            DoorsCount = 5,
                            EngineCapacity = 2.0,
                            FuelType = "Hybrid",
                            GearboxType = "Automatic",
                            ImagePath = "xc40.jpg",
                            Model = "XC40",
                            PricePerDay = 350m,
                            SeatsCount = 5,
                            Segment = "SUV",
                            TrunkCapacity = 452
                        },
                        new
                        {
                            IdCar = "C32",
                            BodyType = "SUV",
                            Brand = "Volvo",
                            DoorsCount = 5,
                            EngineCapacity = 2.0,
                            FuelType = "Diesel",
                            GearboxType = "Automatic",
                            ImagePath = "xc60.jpg",
                            Model = "XC60",
                            PricePerDay = 450m,
                            SeatsCount = 5,
                            Segment = "SUV",
                            TrunkCapacity = 483
                        },
                        new
                        {
                            IdCar = "C33",
                            BodyType = "SUV",
                            Brand = "Volvo",
                            DoorsCount = 5,
                            EngineCapacity = 2.0,
                            FuelType = "Diesel",
                            GearboxType = "Automatic",
                            ImagePath = "/Images/VolvoXC90.png",
                            Model = "XC90",
                            PricePerDay = 650m,
                            SeatsCount = 7,
                            Segment = "SUV",
                            TrunkCapacity = 640
                        },
                        new
                        {
                            IdCar = "C34",
                            BodyType = "Hatchback",
                            Brand = "Renault",
                            DoorsCount = 5,
                            EngineCapacity = 1.0,
                            FuelType = "Petrol",
                            GearboxType = "Manual",
                            ImagePath = "clio.jpg",
                            Model = "Clio",
                            PricePerDay = 120m,
                            SeatsCount = 5,
                            Segment = "B",
                            TrunkCapacity = 391
                        });
                });

            modelBuilder.Entity("CarRentalApp.Models.CarFleet", b =>
                {
                    b.Property<string>("Vin")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("CarId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Vin");

                    b.HasIndex("CarId");

                    b.ToTable("CarFleets");

                    b.HasData(
                        new
                        {
                            Vin = "VIN12345678901234",
                            CarId = "C1",
                            IsAvailable = true,
                            Mileage = 15000,
                            RegistrationNumber = "KR12345"
                        },
                        new
                        {
                            Vin = "VIN98765432109876",
                            CarId = "C2",
                            IsAvailable = true,
                            Mileage = 5000,
                            RegistrationNumber = "WA54321"
                        },
                        new
                        {
                            Vin = "VIN00000000000000",
                            CarId = "C3",
                            IsAvailable = false,
                            Mileage = 1200,
                            RegistrationNumber = "PO99999"
                        },
                        new
                        {
                            Vin = "SKO3OCT0000000001",
                            CarId = "C4",
                            IsAvailable = true,
                            Mileage = 45200,
                            RegistrationNumber = "S3RAVEN"
                        },
                        new
                        {
                            Vin = "SKO3OCT0000000002",
                            CarId = "C4",
                            IsAvailable = true,
                            Mileage = 58000,
                            RegistrationNumber = "KR10002"
                        },
                        new
                        {
                            Vin = "SKO3OCT0000000003",
                            CarId = "C4",
                            IsAvailable = false,
                            Mileage = 92500,
                            RegistrationNumber = "KR10003"
                        },
                        new
                        {
                            Vin = "VW8GOLF0000000004",
                            CarId = "C14",
                            IsAvailable = true,
                            Mileage = 12300,
                            RegistrationNumber = "WA20004"
                        },
                        new
                        {
                            Vin = "VW9PASS0000000005",
                            CarId = "C17",
                            IsAvailable = true,
                            Mileage = 850,
                            RegistrationNumber = "WA20005"
                        },
                        new
                        {
                            Vin = "AUDRS300000000006",
                            CarId = "C24",
                            IsAvailable = true,
                            Mileage = 5200,
                            RegistrationNumber = "PO30006"
                        },
                        new
                        {
                            Vin = "AUDA4000000000007",
                            CarId = "C25",
                            IsAvailable = true,
                            Mileage = 24000,
                            RegistrationNumber = "PO30007"
                        },
                        new
                        {
                            Vin = "VOLXC900000000008",
                            CarId = "C33",
                            IsAvailable = true,
                            Mileage = 15000,
                            RegistrationNumber = "DW40008"
                        },
                        new
                        {
                            Vin = "KIASPOR0000000009",
                            CarId = "C29",
                            IsAvailable = false,
                            Mileage = 33100,
                            RegistrationNumber = "GD50009"
                        },
                        new
                        {
                            Vin = "TESMOD30000000010",
                            CarId = "C3",
                            IsAvailable = true,
                            Mileage = 21000,
                            RegistrationNumber = "EL60010"
                        });
                });

            modelBuilder.Entity("CarRentalApp.Models.Client", b =>
                {
                    b.Property<int>("ClientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientID"));

                    b.Property<string>("ApartmentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ClientID");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientID = 1,
                            City = "Kraków",
                            Country = "Poland",
                            Email = "jan@wp.pl",
                            FirstName = "Jan",
                            HouseNumber = "5",
                            LastName = "Kowalski",
                            Password = "123",
                            Phone = "111222333",
                            PostalCode = "31-000",
                            Street = "Długa",
                            Username = "jkowalski"
                        },
                        new
                        {
                            ClientID = 2,
                            City = "Warszawa",
                            Country = "Poland",
                            Email = "anna@wp.pl",
                            FirstName = "Anna",
                            HouseNumber = "10",
                            LastName = "Nowak",
                            Password = "123",
                            Phone = "444555666",
                            PostalCode = "00-001",
                            Street = "Prosta",
                            Username = "anowak"
                        },
                        new
                        {
                            ClientID = 3,
                            City = "Gdańsk",
                            Country = "Poland",
                            Email = "marek@wp.pl",
                            FirstName = "Marek",
                            HouseNumber = "1",
                            LastName = "Wójcik",
                            Password = "123",
                            Phone = "777888999",
                            PostalCode = "80-000",
                            Street = "Morska",
                            Username = "mwojcik"
                        },
                        new
                        {
                            ClientID = 4,
                            City = "Warszawa",
                            Country = "Poland",
                            Email = "rl9@bramki.pl",
                            FirstName = "Robert",
                            HouseNumber = "44",
                            LastName = "Lewandowski",
                            Password = "999",
                            Phone = "999888777",
                            PostalCode = "00-001",
                            Street = "Złota",
                            Username = "rlewandowski"
                        },
                        new
                        {
                            ClientID = 5,
                            City = "Wrocław",
                            Country = "Poland",
                            Email = "maria@science.pl",
                            FirstName = "Maria",
                            HouseNumber = "102",
                            LastName = "Skłodowska",
                            Password = "rad",
                            Phone = "112233445",
                            PostalCode = "50-100",
                            Street = "Główna",
                            Username = "msklodowska"
                        },
                        new
                        {
                            ClientID = 6,
                            City = "Łódź",
                            Country = "Poland",
                            Email = "zibi@sport.pl",
                            FirstName = "Zbigniew",
                            HouseNumber = "15",
                            LastName = "Boniek",
                            Password = "pzpn",
                            Phone = "666555444",
                            PostalCode = "90-001",
                            Street = "Piotrkowska",
                            Username = "zboniek"
                        },
                        new
                        {
                            ClientID = 7,
                            City = "Gdynia",
                            Country = "Poland",
                            Email = "parostatek@muzyka.pl",
                            FirstName = "Krzysztof",
                            HouseNumber = "7",
                            LastName = "Krawczyk",
                            Password = "rejs",
                            Phone = "555000555",
                            PostalCode = "81-100",
                            Street = "Morska",
                            Username = "kkrawczyk"
                        },
                        new
                        {
                            ClientID = 8,
                            City = "Dąbrowa Górnicza",
                            Country = "Poland",
                            Email = "dawid@koncert.pl",
                            FirstName = "Dawid",
                            HouseNumber = "3",
                            LastName = "Podsiadło",
                            Password = "malomiasteczkowy",
                            Phone = "123123123",
                            PostalCode = "41-300",
                            Street = "Krótka",
                            Username = "dpodsiadlo"
                        });
                });

            modelBuilder.Entity("CarRentalApp.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CarVin")
                        .IsRequired()
                        .HasColumnType("nvarchar(17)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarVin");

                    b.HasIndex("ClientId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarVin = "VIN12345678901234",
                            ClientId = 1,
                            EndDate = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 450m,
                            WorkerId = 1
                        },
                        new
                        {
                            Id = 2,
                            CarVin = "VIN98765432109876",
                            ClientId = 2,
                            EndDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 900m,
                            WorkerId = 2
                        },
                        new
                        {
                            Id = 3,
                            CarVin = "VIN00000000000000",
                            ClientId = 3,
                            EndDate = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 3150m,
                            WorkerId = 1
                        },
                        new
                        {
                            Id = 4,
                            CarVin = "SKO3OCT0000000001",
                            ClientId = 4,
                            EndDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 1800m,
                            WorkerId = 4
                        },
                        new
                        {
                            Id = 5,
                            CarVin = "VW8GOLF0000000004",
                            ClientId = 5,
                            EndDate = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 1050m,
                            WorkerId = 5
                        },
                        new
                        {
                            Id = 6,
                            CarVin = "AUDRS300000000006",
                            ClientId = 6,
                            EndDate = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 1700m,
                            WorkerId = 6
                        },
                        new
                        {
                            Id = 7,
                            CarVin = "VOLXC900000000008",
                            ClientId = 7,
                            EndDate = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 6500m,
                            WorkerId = 7
                        },
                        new
                        {
                            Id = 8,
                            CarVin = "TESMOD30000000010",
                            ClientId = 8,
                            EndDate = new DateTime(2026, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 900m,
                            WorkerId = 8
                        });
                });

            modelBuilder.Entity("CarRentalApp.Models.Worker", b =>
                {
                    b.Property<int>("WorkerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkerID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("WorkerID");

                    b.ToTable("Workers");

                    b.HasData(
                        new
                        {
                            WorkerID = 1,
                            FirstName = "Adam",
                            LastName = "Kierownik",
                            Password = "admin_password",
                            Position = "Manager",
                            Username = "admin"
                        },
                        new
                        {
                            WorkerID = 2,
                            FirstName = "Ewa",
                            LastName = "Pracownik",
                            Password = "staff_password",
                            Position = "Sales Assistant",
                            Username = "staff1"
                        },
                        new
                        {
                            WorkerID = 3,
                            FirstName = "Piotr",
                            LastName = "Serwisant",
                            Password = "staff_password",
                            Position = "Technician",
                            Username = "staff2"
                        },
                        new
                        {
                            WorkerID = 4,
                            FirstName = "Marek",
                            LastName = "Mostowiak",
                            Password = "kartony",
                            Position = "Specjalista ds. Wynajmu",
                            Username = "mmostowiak"
                        },
                        new
                        {
                            WorkerID = 5,
                            FirstName = "Beata",
                            LastName = "Kozidrak",
                            Password = "diva",
                            Position = "Recepcjonistka",
                            Username = "bkozidrak"
                        },
                        new
                        {
                            WorkerID = 6,
                            FirstName = "Robert",
                            LastName = "Makłowicz",
                            Password = "koper",
                            Position = "Koordynator Logistyki",
                            Username = "rmaklowicz"
                        },
                        new
                        {
                            WorkerID = 7,
                            FirstName = "Magda",
                            LastName = "Gessler",
                            Password = "cebula",
                            Position = "Kontroler Jakości Aut",
                            Username = "mgessler"
                        },
                        new
                        {
                            WorkerID = 8,
                            FirstName = "Jerzy",
                            LastName = "Dudek",
                            Password = "dance",
                            Position = "Manager Floty",
                            Username = "jdudek"
                        });
                });

            modelBuilder.Entity("CarRentalApp.Models.CarFleet", b =>
                {
                    b.HasOne("CarRentalApp.Models.Car", "Car")
                        .WithMany("FleetUnits")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("CarRentalApp.Models.Reservation", b =>
                {
                    b.HasOne("CarRentalApp.Models.CarFleet", "CarFleet")
                        .WithMany("Reservations")
                        .HasForeignKey("CarVin")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRentalApp.Models.Client", "Client")
                        .WithMany("Reservations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRentalApp.Models.Worker", "Worker")
                        .WithMany("Reservations")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarFleet");

                    b.Navigation("Client");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("CarRentalApp.Models.Car", b =>
                {
                    b.Navigation("FleetUnits");
                });

            modelBuilder.Entity("CarRentalApp.Models.CarFleet", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("CarRentalApp.Models.Client", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("CarRentalApp.Models.Worker", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
